[build]
  command = "hugo build --config=hugo.toml --minify && tailwindcss -i src/css/styles.css -o static/css/styles.css"
  publish = "public"

[context.deploy-preview]
  command = "npm run start:production"

[context.production.environment]
  HUGO_BASEURL = "https://febriansyah10969.netlify.app/"

[dev]
  framework = "hugo"
  targetPort = 3000
