[build]
  command = "npm run start:production"
  publish = "public"

[context.deploy-preview]
  command = "npm run start:production"

[context.production.environment]
  HUGO_BASEURL = "https://febriansyah10969.netlify.app/"

[dev]
  framework = "hugo"
  targetPort = 3000
